apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: strapi-lb
  labels:
    app: strapi
    tier: backend
spec:
  rules:
    - host: strapi.stage.ur.se
      http:
        paths:
          - backend:
              serviceName: strapi
              servicePort: 1337