apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi-lb
spec:
  rules:
    - host: strapi.stage.ur.se
      http:
        paths:
          - backend:
              serviceName: strapi
              servicePort: 1337