namespace: fleet-strapi
targetCustomizations:
- name: test
  clusterSelector:
    matchLabels:
      env: test
  kustomize:
    dir: overlays/test

- name: stage
  clusterSelector:
    matchLabels:
      env: stage
  kustomize:
    dir: overlays/stage

- name: production
  clusterSelector:
    matchLabels:
      env: production
  kustomize:
    dir: overlays/production

diff:
  comparePatches:
  - apiVersion: v1
    kind: Service
    name: mongo
    operations:
    - {"op":"remove", "path":"metadata/annotations/objectset.rio.cattle.io/id"}
    - {"op":"remove", "path":"/spec/selector/app"}
    - {"op":"remove", "path":"/spec/selector/tier"}
  - apiVersion: v1
    kind: Service
    name: mongo-pods
    operations:
    - {"op":"remove", "path":"/spec/selector/app"}
    - {"op":"remove", "path":"/spec/selector/tier"}