apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config-map
data:
  # Enable free monitoring, run db.enableFreeMonitoring from mongo shell to get URL
  init.js: |
    db.enableFreeMonitoring();

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongod.conf: |+
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: 1
