apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  selector:
    matchLabels:
      app: strapi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: strapi
        tier: backend
    spec:
      containers:
      - name: strapi
        image: strapi/strapi:3.6.1-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: strapi-config-map
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: 'mongo-auth'
              key: 'password'
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: 'mongo-auth'
              key: 'username'